spring:
  application:
    name: jpaboard
  datasource:
    url: jdbc:mysql://localhost:3306/jpaboard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '0000' # 0000만 넣으면 숫자로 인식하니 ''로 감싸주기.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create # ?? create, validate, none ? ??? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect # MySQL 8 ??

  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: info

server:
  port: 8087

jwt:
  secret: DadFuFN4Oui8BfV3SCFj6R9fyJ9hD45E6AGFsXgFsRhTfYdSdS #